[versions]
agp = "8.7.3"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
roomRuntime = "2.6.1"

[libraries]
junit = { group = "junit", firstName = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", firstName = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", firstName = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", firstName = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", firstName = "material", version.ref = "material" }
activity = { group = "androidx.activity", firstName = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", firstName = "constraintlayout", version.ref = "constraintlayout" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

